### ISSUE TITLE
Nápověda

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-dokuwiki#13]
Šlo by k tomu nějak zpracovat nápovědu... Bude krátká, ale aby byla na jednom místě...
https://napoveda.skaut.cz/skautis/skautis-dokuwiki

Můžeme to nějak pořešit?

**Comment by jan-stanek** [comment]
Pro začátek se asi může použít README, je celkem aktuální až na stažení pluginu. Nevím, jestli už funguje vytváření release po poslední opravě.

Akorát by asi bylo dobré mít nápovědu jen na jednom místě a z druhého na ni odkázat.
