### ISSUE TITLE
Povolení služeb

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-dokuwiki#14]
Můžeš @jan-stanek do tohodle souboru https://github.com/skaut/skautis-dokuwiki/blob/master/APP%20ID%20-%20povolen%C3%AD%20slu%C5%BEeb.md sepsat které služby jsou pro plugin potřeba?

Po vzoru https://github.com/skaut/skautis-integration/blob/master/APP%20ID%20-%20povolen%C3%AD%20slu%C5%BEeb.md

Děkuji

**Comment by jan-stanek** [comment]
Doplněno, klidně ho asi můžeme dát rovnou do nápovědy, jsou jen 2 a rozšiřovat se asi nebudou.
