### ISSUE TITLE
Uživatelská jména

### ISSUE THREAD

**Issue by jan-stanek** [skaut/skautis-dokuwiki#9]
Chce to něco vymyslet s usernamy.

Uživatelé, kteří se přihlásí přes skautIS mají username ve tvaru skautisXXXX (XXXX = ID_User). Aby se toto nezobrazovalo uživateli, zapisuje se při přihlášení do proměnné určené pro username celé jméno. Jméno přihlášeného uživatele se potom vypisuje takto:
![spatne](https://user-images.githubusercontent.com/11959693/32957673-b139d1e0-cbbc-11e7-81db-842c322a8046.png)

Udělal jsem úpravu, aby se tam zobrazovalo username a u skautIS uživatelům skautIS username.

U obou způsobů je ale problém s tím, že když chci konkrétním uživatelům nastavit oprávnění, tak musím zadat to, co se vypisuje v závorkách, ne skutečný username v systému.

Stávající způsob řeší problém, že může nastat kolize mezi skautIS uživateli a standardními v dokuwiki, ale potom stačí aby měli uživatelé stejné jméno a příjmení a budou mít stejná oprávnění (pokud je nastavuji přímo pro uživatele, ne skupinu).

Bohužel nepomůže ani to, kdyby se všude používalo skautIS username, protože dokuwiki nepodporuje v username mezery, diakritiku, apod., pokud to nějak převedeme, tak nám může vzniknout kolize i mezi skautIS uživateli.

**Comment by jan-stanek** [comment]
Nejjednodušší a nejčistší mi přijde používat tam to skautisXXXX. I když to není moc hezké pro uživatele.

Nebo očistit skautIS username a k němu přidat ID_User - v tabulce s oprávněními by aspoň bylo poznat, komu bylo oprávnění přiděleno.

**Comment by jerrysohn** [comment]
Na Křižovatce se tohle řeší tak, že se vezme UserName uživatele ze skautISu, pak se "očistí" (odebere se diakritika a mezery), a pak se za něj doplní ID_User. Takže z toho vyjde např. u mě "jerrysohn61" - což je docela dobře čitelné a je z toho rozumně poznatelné, co to je za login (aspoň přibližně).

**Comment by kalich5** [comment]
@jan-stanek je to někde nasazené na otestování?

**Comment by jan-stanek** [comment]
Testovací mám jen na localhost, s normálním skautIS třeba tady: https://volyne.skauting.cz/wiki/

**Comment by kalich5** [comment]
super :-)
